# testRevathi.py # Use Pytest using Page Object Model.
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.firefox.service import Service
from webdriver_manager.firefox import GeckoDriverManager
from Test_Data.data import Revathi_Data
from Test_Locators.locators import Revathi_Locators
from time import sleep
import pytest

class Test_Revathi:
    url = " "
    @pytest.fixture  # Booting method for running the Pytest test cases
    def boot(self):
        self.driver = webdriver.Firefox(service = Service(GeckoDriverManager().install()))
        yield
        self.driver.close()

    def login(self, boot):
        self.driver.implicitly_wait(10)
        self.driver.get(Revathi_Data().B)
        self.driver.find_element(by = By.NAME, value = Revathi_Locators().username_input_box).send_keys(Revathi_Data().C)
        self.driver.find_element(by = By.NAME, value = Revathi_Locators().password_input_box).send_keys(Revathi_Data().D)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().submit_button).click()
        assert (self.driver.title == Revathi_Data().A)
        print("Status = Successful")

    def test_pim_01(self, boot):
        self.driver.implicitly_wait(10)
        self.login(self)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().search_button).send_keys(Revathi_Data().m1)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().search_button).send_keys(Revathi_Data().m2)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().search_button).send_keys(Revathi_Data().m3)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().search_button).send_keys(Revathi_Data().m4)
        self.driver.find_element(by = By.XPATH, value =Revathi_Locators().search_button).send_keys(Revathi_Data().m5)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().search_button).send_keys(Revathi_Data().m6)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().search_button).send_keys(Revathi_Data().m7)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().search_button).send_keys(Revathi_Data().m8)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().search_button).send_keys(Revathi_Data().m9)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().search_button).send_keys(Revathi_Data().m10)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().search_button).send_keys(Revathi_Data().m11)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().search_button).click()
        self.driver.implicitly_wait(10)
        assert (self.driver.title == Revathi_Data().A)
        print("Status :- [Successful].")

    def test_pim_02(self,boot):
        self.driver.implicitly_wait(10)
        self.login(self)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R33).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R34).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R35).send_keys(Revathi_Data().m28)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R36).send_keys(Revathi_Data().m29)
        self.driver.implicitly_wait(10)
        assert (self.driver.title == Revathi_Data().A)
        print("Status = Successful")
            

    
    def test_pim_03(self,boot):
        self.driver.implicitly_wait(10)
        self.login(self) 
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().Pim_button).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R1).click()
        self.driver.find_element(by = By.NAME, value = Revathi_Locators().R2).send_keys(Revathi_Data().m12)
        self.driver.find_element(by = By.NAME, value = Revathi_Locators().R3).send_keys(Revathi_Data().m13)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R4).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R5).send_keys(Revathi_Data().m14)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R6).send_keys(Revathi_Data().m15)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R7).send_keys(Revathi_Data().m16)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R8).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R9).click()
        self.driver.implicitly_wait(10)
        assert (self.driver.title == Revathi_Data().A)
        print("Status = Successful")


    def test_pim_04(self,boot):
        self.driver.implicitly_wait(10)
        self.login(self) 
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().Pim_button).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R1).click()
        self.driver.find_element(by = By.NAME, value = Revathi_Locators().R2).send_keys(Revathi_Data().m12)
        self.driver.find_element(by = By.NAME, value = Revathi_Locators().R3).send_keys(Revathi_Data().m13)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R10).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R9).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R13).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R14).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R15).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R16).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R17).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R18).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R19).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R20).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R21).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R22).click()
        self.driver.implicitly_wait(10)
        assert (self.driver.title == Revathi_Data().A)
        print("Status = Successful")

    def test_pim_05(self,boot):
        self.driver.implicitly_wait(10)
        self.login(self)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().Pim_button).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R1).click()
        self.driver.find_element(by = By.NAME, value = Revathi_Locators().R2).send_keys(Revathi_Data().m12)
        self.driver.find_element(by = By.NAME, value = Revathi_Locators().R3).send_keys(Revathi_Data().m13)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R10).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R9).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R23).send_keys(Revathi_Data().m18)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R24).send_keys(Revathi_Data().m19)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R25).send_keys(Revathi_Data().m20)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R26).send_keys(Revathi_Data().m21)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R27).send_keys(Revathi_Data().m22)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R28).send_keys(Revathi_Data().m23)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R29).send_keys(Revathi_Data().m24)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R30).send_keys(Revathi_Data().m25)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R31).send_keys(Revathi_Data().m26)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R32).click()
        self.driver.implicitly_wait(10)
        assert (self.driver.title == Revathi_Data().A)
        print("Status = Successful")

    def test_pim_06(self,boot):
        self.driver.implicitly_wait(10)
        self.login(self)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().Pim_button).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R1).click()
        self.driver.find_element(by = By.NAME, value = Revathi_Locators().R2).send_keys(Revathi_Data().m12)
        self.driver.find_element(by = By.NAME, value = Revathi_Locators().R3).send_keys(Revathi_Data().m13)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R10).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R9).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R13).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R37).send_keys(Revathi_Data().m30)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R38).send_keys(Revathi_Data().m31)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R39).send_keys(Revathi_Data().m32)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R40).send_keys(Revathi_Data().m33)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R41).send_keys(Revathi_Data().m34)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R42).send_keys(Revathi_Data().m35)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R43).click()
        self.driver.implicitly_wait(10)
        assert (self.driver.title == Revathi_Data().A)
        print("Status = Successful")

    def test_pim_07(self,boot):
        self.driver.implicitly_wait(10)
        self.login(self)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().Pim_button).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R1).click()
        self.driver.find_element(by = By.NAME, value = Revathi_Locators().R2).send_keys(Revathi_Data().m12)
        self.driver.find_element(by = By.NAME, value = Revathi_Locators().R3).send_keys(Revathi_Data().m13)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R10).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R9).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R14).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R44).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R45).send_keys(Revathi_Data().m36)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R46).send_keys(Revathi_Data().m37)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R47).click()
        self.driver.implicitly_wait(10)
        assert (self.driver.title == Revathi_Data().A)
        print("Status = Successful")

    def test_pim_08(self,boot):
        self.driver.implicitly_wait(10)
        self.login(self)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().Pim_button).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R1).click()
        self.driver.find_element(by = By.NAME, value = Revathi_Locators().R2).send_keys(Revathi_Data().m12)
        self.driver.find_element(by = By.NAME, value = Revathi_Locators().R3).send_keys(Revathi_Data().m13)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R10).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R9).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R15).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R48).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R49).send_keys(Revathi_Data().m38)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R50).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R51).send_keys(Revathi_Data().m39)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R52).click()
        self.driver.implicitly_wait(10)
        assert (self.driver.title == Revathi_Data().A)
        print("Status = Successful")

    def test_pim_09(self,boot):
        self.driver.implicitly_wait(10)
        self.login(self)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().Pim_button).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R1).click()
        self.driver.find_element(by = By.NAME, value = Revathi_Locators().R2).send_keys(Revathi_Data().m12)
        self.driver.find_element(by = By.NAME, value = Revathi_Locators().R3).send_keys(Revathi_Data().m13)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R10).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R9).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R17).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R53).send_keys(Revathi_Data().m40)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R54).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R55).send_keys(Revathi_Data().m41)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R56).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R57).send_keys(Revathi_Data().m42)        
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R58).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R59).send_keys(Revathi_Data().m43)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R60).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R61).send_keys(Revathi_Data().m44)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R62).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R63).send_keys(Revathi_Data().m45)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R64).send_keys(Revathi_Data().m46)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R65).click()
        self.driver.implicitly_wait(10)
        assert (self.driver.title == Revathi_Data().A)
        print("Status = Successful")


    def test_pim_10(self,boot):
        self.driver.implicitly_wait(10)
        self.login(self)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().Pim_button).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R1).click()
        self.driver.find_element(by = By.NAME, value = Revathi_Locators().R2).send_keys(Revathi_Data().m12)
        self.driver.find_element(by = By.NAME, value = Revathi_Locators().R3).send_keys(Revathi_Data().m13)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R10).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R9).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R17).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R66).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R67).send_keys(Revathi_Data().m47)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R68).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R69).send_keys(Revathi_Data().m48)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R70).send_keys(Revathi_Data().m49)        
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R71).click()
        self.driver.implicitly_wait(10)
        assert (self.driver.title == Revathi_Data().A)
        print("Status = Successful")

    def test_pim_11(self,boot):
        self.driver.implicitly_wait(10)
        self.login(self)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().Pim_button).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R1).click()
        self.driver.find_element(by = By.NAME, value = Revathi_Locators().R2).send_keys(Revathi_Data().m12)
        self.driver.find_element(by = By.NAME, value = Revathi_Locators().R3).send_keys(Revathi_Data().m13)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R10).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R9).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R17).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R66).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R67).send_keys(Revathi_Data().m47)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R68).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R69).send_keys(Revathi_Data().m48)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R70).send_keys(Revathi_Data().m49)        
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R71).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R72).click()
        self.driver.implicitly_wait(10)
        assert (self.driver.title == Revathi_Data().A)
        print("Status = Successful")


    def test_pim_12(self,boot):
        self.driver.implicitly_wait(10)
        self.login(self)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().Pim_button).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R1).click()
        self.driver.find_element(by = By.NAME, value = Revathi_Locators().R2).send_keys(Revathi_Data().m12)
        self.driver.find_element(by = By.NAME, value = Revathi_Locators().R3).send_keys(Revathi_Data().m13)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R10).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R9).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R18).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R73).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R74).send_keys(Revathi_Data().m50)        
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R75).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R76).send_keys(Revathi_Data().m51)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R77).click()       
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R78).send_keys(Revathi_Data().m52)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R79).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R80).send_keys(Revathi_Data().m53)        
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R81).send_keys(Revathi_Data().m54)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R82).click() #direct deposit details
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R83).send_keys(Revathi_Data().m55)        
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R84).click()
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R85).send_keys(Revathi_Data().m56)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R86).send_keys(Revathi_Data().m57)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R87).send_keys(Revathi_Data().m58)
        self.driver.find_element(by = By.XPATH, value = Revathi_Locators().R88).click()
        self.driver.implicitly_wait(10)
        assert (self.driver.title == Revathi_Data().A)
        print("Status = Successful")




     #pytest -v -s --capture=sys --html=C:\Users\tmztm\Desktop\Project3\Reports\first_1.html testRevathi.py